version: '3'

services:
    db:
        image: mysql:latest
        container_name: adnyamysql
        environment:
            MYSQL_ROOT_PASSWORD: adnya
            MYSQL_DATABASE: adnya
            MYSQL_USER: adnya
            MYSQL_PASSWORD: adnya
        ports:
            - "6033:3306"
        volumes:
            - dbdata:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: adnyaphpmyadmin
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8085:80
volumes:
    dbdata:
