version: "3.9"

services:
  php:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 9090:80

  db_adnya:
    container_name: msqlaadnya
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adnya

  phpmyadminadnya:
    container_name: phpadminadnya
    links: db_adnya
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9091:80
    environment:
      - PMA_ARBITRARY=1
